name: Test Flutter iOS

on:
  workflow_dispatch:

jobs:
  flutter-ios:
    runs-on: macos-latest

    steps:
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Check Flutter
        run: |
          flutter --version
          flutter doctor -v

      - name: Create test Flutter project
        run: |
          flutter create --platforms=ios test_app

      - name: Build iOS
        working-directory: test_app
        run: |
          flutter pub get
          flutter build ios --release --no-codesign
